version: '3.0'
services:
  nginx_test:
    image: nginx_test:1.0.0
    restart: always
    volumes:
      - ./certs:/usr/share/certs
      - ./site:/usr/share/nginx/html:ro
      - ./sites-available:/etc/nginx/sites-available:ro
      - ./logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 9100:9100
      - 9143:9143
      - 9200:9200
      - 9243:9243
     