server {
	# 不重要测试用 用你自己的就好
	listen 8095 ssl;

	# 不重要测试用 用你自己的就好
	ssl_certificate /usr/share/certs/cert_site1.pem;
	ssl_certificate_key /usr/share/certs/key_site1.pem;

	charset utf-8;

	set $should_proxy 0;
	set $should_proxy_special 0;
	# 标准产品线 开始 #
	if ($http_referer ~* "/app/ct_|/ct_|/viewer-r|/viewer_rr|/app/library|/app/video_film-|/app/report|/app/dr_|/app/mr_head|/ai4d_client|/novnc|/app/center|/app/basepage|/vnc_export_stl|/app/operate|/app/integrate") {
		set $should_proxy 1;
	}

	if ($request_uri ~* "/app/ct_|/^ct_|/viewer-r|/viewer_rr|/app/library|/app/video_film-|/app/report|/app/dr_|/app/mr_head|/ai4d_client|/novnc|/app/center|/app/basepage|/doge_statics|/RESULT/ssr|^/dcm|/api/v1/user/guest-access|/vnc_export_stl|/app/operate|/app/integrate") {
		set $should_proxy 1;
	}

	if ($request_uri ~* "^/ws/Infervision|^/wslink|^/ai4d_sio|^/ai4d_ws|^/vnc_websockify|^/traefik/ct_") {
		set $should_proxy 1;
	}
	# 标准产品线 结束 #

	# 特殊产品线 开始 #
	if ($http_referer ~* "/viewerX|/app/ct_thorax|/static/js/cornerstoneWADOImageLoader") {
		set $should_proxy_special 1;
	}
	if ($request_uri ~* "/viewerX|/app/ct_thorax|/static/img/predictBtn.png") {
		set $should_proxy_special 1;
	}
	if ($request_uri ~* "^/Infervision") {
		set $should_proxy_special 1;
	}
	if ($request_uri ~* "/app/report") {
		set $should_proxy_special 0;
		set $should_proxy 1;
	}
	# 特殊产品线 结束 #

	set $connection_upgrade "keep-alive";
	if ($http_upgrade ~* "websocket") {
		set $connection_upgrade "upgrade";
	}

	set $server_infervision_address "10.10.22.23:8000";
	set $server_infervision_address_special "10.10.22.23:3005";

	# # 看你们情况按需配置
	# location =/ {
	# 	rewrite / /app/center/login;
	# }

	location / {
		# add_header Content-Type text/plain;
		# return 200 "Debug Info:
		# server_infervision_address: $server_infervision_address
		# request_uri: $request_uri
		# http_referer: $http_referer
		# should_proxy: $should_proxy
		# ";
		# add_header x-debug $should_proxy always;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header Referer $http_referer;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Server $hostname;
		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection $connection_upgrade;

		if ($should_proxy_special = 1) {
			proxy_pass https://$server_infervision_address_special;
			set $should_proxy 0;
		}
		if ($should_proxy = 1) {
			proxy_pass http://$server_infervision_address;
		}

		# 看你们情况按需配置
		try_files $uri $uri/ =404;
	}
}