server {
	listen 8094;

	# 用来区分请求
	# server_name a.com;

	charset utf-8;

	set $is_infervision_referer 0;
	if ($http_referer ~* infervision) {
		set $is_infervision_referer 1;
	}

	set $has_infervision_cookie 0;
	if ($cookie_infervision = "1") {
		set $has_infervision_cookie 1;
	}

	set $should_proxy 0;
	if ($is_infervision_referer = 1) {
		set $should_proxy 1;
	}
	if ($has_infervision_cookie = 1) {
		set $should_proxy 1;
	}
	set $server_infervision_address "172.16.8.85:8000";

	location /infervision {
		add_header Content-Type text/plain;
		return 200 "123";
		# add_header Set-Cookie "infervision=1; Path=/; HttpOnly";
		# set $captured_path $request_uri;
		# if ($request_uri ~ "^/infervision(.*)") {
		# 	set $captured_path $1;
		# }

		# return 302 $captured_path;
		# add_header Content-Type text/plain;
		# return 200 "Debug Info:
		# server_infervision_address: $server_infervision_address
		# request_uri: $captured_path
		# ";
	}

	# location / {
	# 	# add_header Content-Type text/plain;
	# 	# return 200 "Debug Info:
	# 	# server_infervision_address: $server_infervision_address
	# 	# request_uri: $request_uri
	# 	# should_proxy: $should_proxy
	# 	# cookie_infervision: $cookie_infervision
	# 	# ";
	# 	proxy_set_header Host $host;
	# 	proxy_set_header X-Real-IP $remote_addr;
	# 	proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	# 	proxy_set_header X-Forwarded-Proto $scheme;
	# 	proxy_set_header Referer $http_referer;
	# 	proxy_set_header X-Forwarded-Host $host;
	# 	proxy_set_header X-Forwarded-Port $server_port;
	# 	proxy_set_header X-Forwarded-Server $hostname;

	# 	if ($should_proxy = 1) {
	# 		proxy_pass http://$server_infervision_address;
	# 	}

	# 	try_files $uri $uri/ =404;
	# }
}